
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testst-3
  description: testing...
  links:
    - url: https://github.com/Kheops-org/testst-3
      title: Source Code
      icon: github
    - url: https://argocd-server-sreez.apps.oc-med.wk.nt.local/applications/sreez/testst-3
      title: ArgoCD Deployment
      icon: cached
    # - url: http://localhost:8090
    #   title: HyperDX Logs and Monitoring
    #   icon: monitor_heart
    - url: http://testst-3-sreez.apps.oc-med.wk.nt.local
      title: Open Application
      icon: Link
    - url: https://devspaces.apps.oc-med.wk.nt.local#https://github.com/Kheops-org/testst-3
      title: VSCode Development Environment
      icon: code
  tags:
    - go
    - sreez
  annotations:
    argocd/app-name: testst-3
    backstage.io/kubernetes-id: testst-3
    github.com/workflows: docker-image.yml
    github.com/project-slug: Kheops-org/testst-3
spec:
  type: service
  system: system:default/examples
  lifecycle: production
  owner: user:default/sylvaintremblay666
